"""ChartSpec: the intermediate representation shared between the
understanding and generation sides of ChartAgent."""

from .chartspec import (
    Axes,
    Axis,
    ChartCoverage,
    ChartFigure,
    ChartFigureItem,
    ChartMetadata,
    ChartSpec,
    ChartSpecCollection,
    ChartType,
    DataPoint,
    FigureLayout,
    FigureSource,
    MAX_COLLECTION_FIGURES,
    MAX_FIGURE_CHARTS,
    MAX_FIGURE_COLUMNS,
    MAX_FIGURE_ID_LENGTH,
    ValidationIssue,
)
from .context import (
    CoverageBasis,
    CoverageStatus,
    GenerationContext,
    GenerationCoverage,
    GenerationMode,
    GenerationSourceScope,
    SelectionBasis,
    context_digest,
    generation_context_schema,
    normalize_generation_context,
)
from .identity import chart_collection_digest, chart_figure_digest, chart_spec_digest

__all__ = [
    "ChartSpec",
    "ChartSpecCollection",
    "ChartFigure",
    "ChartFigureItem",
    "ChartCoverage",
    "FigureSource",
    "FigureLayout",
    "ChartType",
    "ChartMetadata",
    "Axes",
    "Axis",
    "DataPoint",
    "ValidationIssue",
    "chart_spec_digest",
    "chart_figure_digest",
    "chart_collection_digest",
    "MAX_COLLECTION_FIGURES",
    "MAX_FIGURE_CHARTS",
    "MAX_FIGURE_COLUMNS",
    "MAX_FIGURE_ID_LENGTH",
    "CoverageBasis",
    "CoverageStatus",
    "GenerationContext",
    "GenerationCoverage",
    "GenerationMode",
    "GenerationSourceScope",
    "SelectionBasis",
    "context_digest",
    "generation_context_schema",
    "normalize_generation_context",
]
