"""Limits owned by the ChartFigure content model."""

CHART_FIGURE_SCHEMA_VERSION = 2
MAX_CHART_FIGURE_BYTES = 64 * 1024
MAX_CHART_FIGURE_ITEMS = 4
MAX_FIGURE_COLUMNS = 2
MAX_CHART_ID_LENGTH = 64
MAX_MEASUREMENT_REFS_PER_CHART = 16
