import { GatewayClientError } from '../api/gateway/transport'

export function toUserMessage(error: unknown): string {
  if (error instanceof GatewayClientError) {
    if (error.code === 'gateway_unavailable') return '无法连接到本地 Gateway，请先启动 Python 服务。'
    if (error.code === 'agent_unavailable' && error.reason === 'missing_configuration') return 'Agent 未配置，请检查项目根目录 .env 中的模型配置。'
    if (error.code === 'agent_unavailable' && error.reason === 'invalid_configuration') return 'Agent 配置无效，请检查模型地址和参数。'
    if (error.code === 'agent_unavailable') return 'Agent 当前不可用，请稍后重试。'
    if (error.code === 'invalid_provider') return '模型来源不受支持，请重新选择 OpenAI 或 Qwen。'
    if (error.code === 'idempotency_conflict') return '请求标识已对应其他内容，请重新提交。'
    if (error.code === 'run_not_terminal') return '运行尚未结束，暂时不能重试。'
    if (error.code === 'recovery_blocked') return error.reason === 'operation_outcome_uncertain' ? '运行在一个操作边界中断，结果无法安全确认，请使用“重试本次运行”。' : '该运行暂时无法继续执行，请使用“重试本次运行”。'
    if (error.code === 'recovery_unavailable' || error.code === 'checkpoint_expired' || error.code === 'unsupported_checkpoint_version') return '该运行没有可用的继续执行检查点，请使用“重试本次运行”。'
    if (error.code === 'resume_idempotency_conflict') return '恢复请求标识已对应其他恢复操作，请重新点击继续执行。'
    if (error.code === 'history_gap') return '执行历史存在缺口，当前只能查看已保留部分。'
    if (error.code === 'session_not_found') return '会话不存在，可能已被删除。'
    if (error.code === 'session_exists') return '会话名称已存在，请换一个名称。'
    if (error.code === 'session_busy') return '会话正在运行 Agent，请等待本次运行结束后再删除。'
    if (error.code === 'run_unavailable' || error.code === 'event_history_unavailable') return '这条执行记录已不可用，当前只保留可恢复的会话内容。'
    if (error.code === 'evaluation_not_found') return '评测批次不存在，可能已经被移除。'
    if (error.code === 'evaluation_case_not_found') return '评测 case 不存在或尚未写入索引。'
    if (error.code === 'evaluation_history_unavailable') return '该 case 的运行历史暂时不可读，但阶段摘要仍可查看。'
    if (error.code === 'evaluation_resource_not_found' || error.code === 'evaluation_resource_unavailable') return '评测证据不存在、已过期或暂时不可用。'
    if (error.code === 'evaluation_not_ready') return '评测批次仍在写入，请稍后刷新。'
    if (error.code === 'evaluation_schema_invalid' || error.code === 'evaluation_schema_unsupported') return '评测批次格式不受支持，已保留其它可用记录。'
    if (error.code === 'source_binding_required') return '当前会话有多个活动源，请在右侧勾选要使用的附件后重试。'
    if (error.code === 'attachment_not_found') return '附件不存在或不属于当前会话。'
    if (error.code === 'attachment_unavailable') return '附件源文件不可用，请重新上传。'
    if (error.code === 'attachment_storage_error') return '附件文件操作失败，请稍后重试。'
    if (error.code === 'unsupported_media_type' || error.code === 'invalid_image') return '图片格式无法识别，请选择 PNG、JPEG、GIF 或 WebP。'
    if (error.code === 'attachment_too_large' || error.code === 'attachment_storage_limit') return '图片或当前会话的附件总量超过限制。'
    if (error.code === 'invalid_filename') return '图片文件名无效，请重命名后重试。'
    if (error.code === 'invalid_request') return '请求内容无效，请检查后重试。'
    return '本地服务处理失败，请稍后重试。'
  }
  return '操作失败，请稍后重试。'
}
