"""Version 1 size limits for Figura chart content."""

import sys

CHART_SPEC_SCHEMA_VERSION = 1
MAX_DATA_POINTS = 512
MAX_TEXT_LENGTH = 160
MAX_ISSUES = 32
MAX_ISSUE_CODE_LENGTH = 64
MAX_ISSUE_PATH_BYTES = 256
MAX_ISSUE_MESSAGE_LENGTH = 240
MAX_CHART_SPEC_DATA_BYTES = 256 * 1024
MAX_FINITE_NUMBER = sys.float_info.max
MAX_DATA_POINTS = 512
MAX_TEXT_LENGTH = 160
MAX_ISSUES = 32
MAX_ISSUE_CODE_LENGTH = 64
MAX_ISSUE_PATH_BYTES = 256
MAX_ISSUE_MESSAGE_LENGTH = 240
MAX_CHART_SPEC_DATA_BYTES = 256 * 1024
